title = "Minimization Standard Form"
type = "min"

[decisionVariables]
num = 6

objectiveFunction = [
    0.48,
    0.32,
    0.53,
    0.28,
    0.43,
    0.04,
]

[constraints]
num = 4
coefficients = [
    [0, 0, 1, 1, 0, 0],
    [0, 1, 0, 0, 1, 0],
    [1, 0, 0, 1, 0, 0],
    [1, 1, 1, 1, 1, 1],
]
operations = [
    "gt",
    "gt",
    "gt",
    "gt",
]
rhs = [
    1,
    1,
    1,
    15000,
]
