title = "Minimization Standard Form"
type = "min"

[decisionVariables]
num = 2

objectiveFunction = [
    60, 50
]

[constraints]
num = 3
coefficients = [
    [8, 16],
    [60, 40],
    [2, 2],
]
operations = [
    "gt",
    "gt",
    "gt",
]
rhs = [
    200, 960, 40
]