title = "Example 2"
type = "min"

[decisionVariables]
num = 8

objectiveFunction = [
    1020, 1500, 2100, 1070, 1125, 1350, 1750, 1090,
]

[constraints]
num = 6
coefficients = [
    [1, 1, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 1, 1, 1],
    [1, 0, 0, 0, 1, 0, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 1, 0, 0, 0, 1],
]
operations = [
    "gt",
    "gt",
    "lt",
    "lt",
    "lt",
    "lt",
]
rhs = [
    5500,
    7500,
    5000,
    3000,
    2000,
    3000,
]
